enable silent rules when building
* Note: ONLY configure.ac and stage2/Makefile.am were manually modified.
  The other files were generated by autotools.

diff --git a/stage2/Makefile.am b/stage2/Makefile.am
--- a/stage2/Makefile.am
+++ b/stage2/Makefile.am
@@ -3,6 +3,12 @@
 TESTS = 
 noinst_SCRIPTS = $(TESTS)
 
+# For silencing OBJCOPY output.
+AM_V_OBJCOPY_0 = @echo "  OBJ    $@";$(OBJCOPY)
+AM_V_OBJCOPY_1 = $(OBJCOPY)
+AM_V_OBJCOPY_  = $(AM_V_OBJCOPY_$(AM_DEFAULT_VERBOSITY))
+AM_V_OBJCOPY   = $(AM_V_OBJCOPY_$(V))
+
 # For dist target.
 noinst_HEADERS = fat.h filesys.h freebsd.h hercules.h \
 	iso9660.h jfs.h mb_header.h mb_info.h md5.h \
@@ -65,8 +71,8 @@ pre_stage2_exec_LDFLAGS = $(PRE_STAGE2_LINK)
 CLEANFILES = $(datalib_DATA) $(noinst_DATA) $(BUILT_SOURCES)
 
 stage2_size.h: pre_stage2
-	-rm -f stage2_size.h
-	set dummy `ls -l pre_stage2`; \
+	$(AM_V_at)-rm -f stage2_size.h
+	$(AM_V_at)set dummy `ls -l pre_stage2`; \
 	echo "#define STAGE2_SIZE $$6" > stage2_size.h
 
 dosstart_exec_SOURCES = dosstart.S
@@ -76,10 +82,11 @@ dosstart_exec_LDFLAGS = $(START_LINK)
 dosstart_exec-dosstart.$(OBJEXT): stage2_size.h
 
 grub.exe: pre_stage2 dosstart
-	-rm -f grub.exe
-	echo -n -e "\000\000\000\000\000\000\000\000\000\000\000\000" | cat dosstart pre_stage2 - > grub.exe
-	if [ -f ../preset_menu_used ]; then cat ../preset_menu_used >> grub.exe ;fi
-	dd if=/dev/zero bs=4128 count=1 >> grub.exe
+	$(AM_V_GEN)
+	$(AM_V_at)-rm -f grub.exe
+	$(AM_V_at)echo -n -e "\000\000\000\000\000\000\000\000\000\000\000\000" | cat dosstart pre_stage2 - > grub.exe
+	$(AM_V_at)if [ -f ../preset_menu_used ]; then cat ../preset_menu_used >> grub.exe ;fi
+	$(AM_V_at)dd if=/dev/zero bs=4128 count=1 >> grub.exe 2>/dev/null || echo "DD failed!"
 
 badgrubstart_exec_SOURCES = badgrubstart.S
 badgrubstart_exec_CCASFLAGS = $(STAGE2_COMPILE)
@@ -88,10 +95,11 @@ badgrubstart_exec_LDFLAGS = $(START_LINK)
 badgrubstart_exec-badgrubstart.$(OBJEXT): stage2_size.h dosstart.S
 
 badgrub.exe: pre_stage2 badgrubstart
-	-rm -f badgrub.exe
-	echo -n -e "\000\000\000\000\000\000\000\000\000\000\000\000" | cat badgrubstart pre_stage2 - > badgrub.exe
-	if [ -f ../preset_menu_used ]; then cat ../preset_menu_used >> badgrub.exe ;fi
-	dd if=/dev/zero bs=4128 count=1 >> badgrub.exe
+	$(AM_V_GEN)
+	$(AM_V_at)-rm -f badgrub.exe
+	$(AM_V_at)echo -n -e "\000\000\000\000\000\000\000\000\000\000\000\000" | cat badgrubstart pre_stage2 - > badgrub.exe
+	$(AM_V_at)if [ -f ../preset_menu_used ]; then cat ../preset_menu_used >> badgrub.exe ;fi
+	$(AM_V_at)dd if=/dev/zero bs=4128 count=1 >> badgrub.exe 2>/dev/null || echo "DD failed!"
 
 grldrstart_exec_SOURCES = grldrstart.S
 grldrstart_exec_CCASFLAGS = $(STAGE2_COMPILE)
@@ -100,9 +108,10 @@ grldrstart_exec_LDFLAGS = $(START_LINK)
 grldrstart_exec-grldrstart.$(OBJEXT): stage2_size.h
 
 grldr: pre_stage2 grldrstart
-	-rm -f grldr
-	echo -n -e "\000\000\000\000\000\000\000\000\000\000\000\000" | cat grldrstart pre_stage2 - > grldr
-	if [ -f ../preset_menu_used ]; then cat ../preset_menu_used >> grldr ;fi
+	$(AM_V_GEN)
+	$(AM_V_at)-rm -f grldr
+	$(AM_V_at)echo -n -e "\000\000\000\000\000\000\000\000\000\000\000\000" | cat grldrstart pre_stage2 - > grldr
+	$(AM_V_at)if [ -f ../preset_menu_used ]; then cat ../preset_menu_used >> grldr ;fi
 
 mbrstart_exec_SOURCES = mbrstart.S
 mbrstart_exec_CCASFLAGS = $(STAGE2_COMPILE)
@@ -111,8 +120,9 @@ mbrstart_exec_LDFLAGS = $(START_LINK)
 mbrstart_exec-mbrstart.$(OBJEXT): stage2_size.h grldrstart.S
 
 grldr.mbr: mbrstart
-	-rm -f grldr.mbr
-	cat mbrstart > grldr.mbr
+	$(AM_V_GEN)
+	$(AM_V_at)-rm -f grldr.mbr
+	$(AM_V_at)cat mbrstart > grldr.mbr
 
 bootlacestart_exec_SOURCES = bootlacestart.S
 bootlacestart_exec_CCASFLAGS = $(STAGE2_COMPILE)
@@ -121,8 +131,9 @@ bootlacestart_exec_LDFLAGS = -nostdlib -Wl,-N -Wl,-Ttext -Wl,08048000 $(BIN_LDFL
 bootlacestart_exec-bootlacestart.$(OBJEXT): stage2_size.h bootlace.inc grldrstart.S
 
 bootlace.com: bootlacestart
-	-rm -f bootlace.com
-	cp bootlacestart bootlace.com && chmod a+x bootlace.com
+	$(AM_V_GEN)
+	$(AM_V_at)-rm -f bootlace.com
+	$(AM_V_at)cp bootlacestart bootlace.com && chmod a+x bootlace.com
 
 hmloadstart_exec_SOURCES = hmloadstart.S
 hmloadstart_exec_CCASFLAGS = $(STAGE2_COMPILE)
@@ -131,12 +142,13 @@ hmloadstart_exec_LDFLAGS = -nostdlib -Wl,-N -Wl,-Ttext -Wl,08048000 $(BIN_LDFLAG
 hmloadstart_exec-hmloadstart.$(OBJEXT): stage2_size.h
 
 hmload.com: hmloadstart
-	-rm -f hmload.com
-	cp hmloadstart hmload.com && chmod a-x hmload.com
+	$(AM_V_GEN)
+	$(AM_V_at)-rm -f hmload.com
+	$(AM_V_at)cp hmloadstart hmload.com && chmod a-x hmload.com
 
 eltorito.sys: eltorito.asm
-	nasm -Ox -f bin -o $@ $< || echo "Failed in building eltorito.sys!"
-	upx --ultra-brute --lzma $@ || upx --ultra-brute $@ || echo "upx command not found!"
+	$(AM_V_at)nasm -Ox -f bin -o $@ $< || echo "Failed in building eltorito.sys!"
+	$(AM_V_at)upx --ultra-brute --lzma $@ || upx --ultra-brute $@ || echo "upx command not found!"
 
 asm.S: a20.inc
 	touch asm.S
@@ -150,9 +162,9 @@ badgrubstart.S: a20.inc
 # General rule for making a raw binary.
 SUFFIXES = .exec
 %: %.exec$(EXEEXT)
-	$(OBJCOPY) -O binary $< $@
-	if [ $@ = pre_stage2 ]; then dd if=pre_stage2 of=pre_stage2_fullsize bs=65536 skip=48 ;fi
-	if [ $@ = pre_stage2 ]; then sed -e "1s/^\x00*//" pre_stage2_fullsize > pre_stage2_tail ;fi
-	if [ $@ = pre_stage2 ]; then set dummy `ls -l pre_stage2_fullsize`; set $$6 `ls -l pre_stage2_tail`; if [ $$1 -le $$6 ]; then set `cmp pre_stage2_fullsize /dev/zero` ; while [ "$$1" != "" ]; do t1="$${1%%[^0-9]*}"; if [ "$$t1" != "" ]; then if [ "$$t1" -gt 2000 ]; then t1=`expr $$t1 - 1`; dd if=pre_stage2_fullsize of=pre_stage2_tail bs=1 skip=$$t1 ; break; fi; fi; shift; done; fi; fi
-	if [ $@ = pre_stage2 ]; then set dummy `ls -l pre_stage2_fullsize`; set $$6 `ls -l pre_stage2_tail`; dd if=pre_stage2 of=pre_stage2_head bs=`expr $$1 - $$6` count=1 ; cat pre_stage2_head pre_stage2_tail > pre_stage2 ;fi
-	if [ $@ = pre_stage2 ]; then echo -n -e "\0260\002\032\0316" >> $@ ;fi
+	$(AM_V_OBJCOPY) -O binary $< $@
+	$(AM_V_at)if [ $@ = pre_stage2 ]; then dd if=pre_stage2 of=pre_stage2_fullsize bs=65536 skip=48 2>/dev/null || echo "DD failed!" ;fi
+	$(AM_V_at)if [ $@ = pre_stage2 ]; then sed -e "1s/^\x00*//" pre_stage2_fullsize > pre_stage2_tail ;fi
+	$(AM_V_at)if [ $@ = pre_stage2 ]; then set dummy `ls -l pre_stage2_fullsize`; set $$6 `ls -l pre_stage2_tail`; if [ $$1 -le $$6 ]; then set `cmp pre_stage2_fullsize /dev/zero` ; while [ "$$1" != "" ]; do t1="$${1%%[^0-9]*}"; if [ "$$t1" != "" ]; then if [ "$$t1" -gt 2000 ]; then t1=`expr $$t1 - 1`; dd if=pre_stage2_fullsize of=pre_stage2_tail bs=1 skip=$$t1  2>/dev/null || echo "DD failed!" ; break; fi; fi; shift; done; fi; fi
+	$(AM_V_at)if [ $@ = pre_stage2 ]; then set dummy `ls -l pre_stage2_fullsize`; set $$6 `ls -l pre_stage2_tail`; dd if=pre_stage2 of=pre_stage2_head bs=`expr $$1 - $$6` count=1 2>/dev/null || echo "DD failed!" ; cat pre_stage2_head pre_stage2_tail > pre_stage2 ;fi
+	$(AM_V_at)if [ $@ = pre_stage2 ]; then echo -n -e "\0260\002\032\0316" >> $@ ;fi
